In [1]:
from sklearn.feature_extraction.text import CountVectorizer

documents = ["Machine learning is amazing!",
             "Deep learning is a subset of machine learning.",
             "Natural language processing is a part of AI.",
             "AI is transforming the world."]

cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = cv.fit_transform(documents)      # Convert text to document-term matrix
print(cv.get_feature_names_out())      # Display remaining words
print(dtm.toarray())                   # Show word counts in documents

['ai' 'learning' 'machine']
[[0 1 1]
 [0 2 1]
 [1 0 0]
 [1 0 0]]


In [7]:
import random
from sklearn.feature_extraction.text import CountVectorizer

# Sample text corpus
documents = ["Machine learning is amazing",
             "Deep learning is a subset of machine learning",
             "Natural Language Processing is a key part of AI"]

# Convert text into a document-term matrix
cv = CountVectorizer(stop_words='english')
dtm = cv.fit_transform(documents)

#Get feature names
feature_names = cv.get_feature_names_out()   # Updated method.

#Generate 10 random words from the vocabulary
for i in range(10):
    random_word_id = random.randint(0, len(feature_names) - 1)    # Use actual vocabulary size
    print(feature_names[random_word_id])

processing
subset
ai
language
deep
key
language
subset
subset
deep


In [17]:
import numpy as np
from sklearn.decomposition import LatentDirichletAllocation 
from sklearn.feature_extraction.text import CountVectorizer

#Sample corpus
documents = ["I love machine learning and data science",
             "Deep learning is a subset of machine learning",
             "I enjoy playing football and watching sports",
             "Sports analytics is an interesting field",
]

#Convert text to document-term matrix
vectorizer = CountVectorizer(stop_words='english')
dtm = vectorizer.fit_transform(documents)

# Train LDA model
lda = LatentDirichletAllocation(n_components=2, random_state=42)        # n_components means document divide into two topic
lda.fit(dtm)

# Get topic distribution for each document
topic_results = lda.transform(dtm) # Shape: (num_docs, num_topics)

# Identify the dominant topic for each document
dominant_topics = topic_results.argmax(axis=1)

# Print results
for i, topic in enumerate(dominant_topics):
    print(f"Document {i+1} is mostly about Topic {topic}")


Document 1 is mostly about Topic 1
Document 2 is mostly about Topic 0
Document 3 is mostly about Topic 1
Document 4 is mostly about Topic 0


In [15]:
len(documents)

4